istio:
  namespace: "istio-system"
  istioCNI:
    enabled: true
  enableStrictMTLS: true 
  gateways:
    egress:
      enabled: true
      namespace: "istio-egress"
      replicas: 1
      autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 5
    ingress:
      enabled: true
      namespace: "istio-ingress"
      replicas: 1
      autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 5
  pilot:
    replicas: 1
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
  meshConfig:
    connectTimeout: "10s"
    ingressControllerMode: "STRICT"
    trustDomain: "cluster.local"
    enablePrometheusMerge: true
    meshMTLS:
      minProtocolVersion: "TLSV1_2"
    enableDNSProxy: false
